### ISSUE TITLE
프로젝트 컨벤션 정리 (git / branch 전략)

### ISSUE THREAD

**Issue by 1eeyerin** [SpartaEnergizerTeam/movie-site#5]
## 🔥 branch 전략 (배민 git flow 참고: https://techblog.woowahan.com/2553/)
main(master): 서비스을 직접 배포하는 역할을 하는 브랜치입니다.
feature(기능): 각 기능 별 개발 브랜치입니다.
develop(개발): feature에서 개발된 내용이 저장되는 브랜치입니다.

## 🔥 git commit 컨벤션
- 커밋 메세지를 잘 작성하면, 우리는 단순히 커밋 이력만 보고서도 현재까지 어떤 개발이 진행되었고, 어떤 커밋에서 문제가 발생했는지 등을 확인할 수 있게 됩니다. 특히나 규모가 큰 개발일수록 이 커밋 메세지는 더욱 중요해집니다.

작업 타입 | 작업내용
-- | --
feat | 해당 파일에 새로운 기능이 생김
fix | 버그 수정
docs | 문서 수정
refactor | 코드 리팩토링
style | 코드 포맷팅, 세미콜론 누락, 코드 변경이 없는 경우
chore | 빌드 업무 수정, 패키지 매니저 수정

**Comment by Ahnjonghyun87** [comment]
이 코멘트로 작성하도록 최대한 노력 해보겠읍니다

**Comment by yeeunseo-dev** [comment]
확인했습니다! 보고 작성해볼게요~~

- 리팩토링 : 코드의 외부 동작을 변경하지 않으면서 코드의 내부 구조를 개선하는 프로세스 (메서드 이름 변경, 중복 코드를 함수나 메서드로 추출하기, 크고 복잡한 함수를 더 작고 관리하기 쉬운 여러 함수로 분리하기, 클래스 구조 재설계하기, 가독성 향상을 위해 변수 이름 바꾸기)

- 코드 포맷팅 : 코드를 작성한 후 해당 코드의 스타일을 문법적 규칙이나 팀의 코딩 규칙에 맞게 조정하는 작업 (들여쓰기 수정, 세미콜론 누락 수정, 라인 길이 조정, 괄호 위치 조정, 변수, 함수, 클래스 이름의 케이싱 수정하기 (예: camelCase, PascalCase, snake_case))

- 빌드 업무 수정 : 프로젝트 빌드 과정을 변경하는 것

- 패키지 매니저 수정 : 프로젝트에서 사용하는 외부 라이브러리나 패키지를 관리하는 설정이나 파일을 변경하는 것
